version: '3.8'

services:
  pyipad:
    image: overcookedpanda/pyipad:latest
    user: "1000:1000"
    ports:
      - "13111:13111" # P2P
      - "13110:13110" # RPC
    volumes:
      - ./data:/data

  pyrinwallet:
    image: overcookedpanda/pyrinwallet:latest
    user: "1000:1000"
