name: Docker Build

on:
  push:
    branches: [ "master", "fix-docker" ]
  pull_request:
    branches: [ "master", "fix-docker" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build the docker image and push
        run: |
          docker build . --file docker/Dockerfile --tag overcookedpanda/pyipad:latest
          docker push overcookedpanda/pyipad:latest